version: "3"
services:
  reverseproxy:
      image: maduflavins/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: maduflavins/udacity-restapi-user
    environment:
      POSTGRESS_USERNAME: 'udermicroservice'
      POSTGRESS_PASSWORD: 'udermicroservice' 
      POSTGRESS_DB: 'postgres' 
      POSTGRESS_HOST: 'udermicroservice.cgmpimwngkbt.us-east-2.rds.amazonaws.com' 
      AWS_REGION: 'postgres' 
      AWS_PROFILE: 'default' 
      AWS_BUCKET: 'udermicroservice'
      JWT_SECRET: 'helloworld'
      URL: "http://localhost:8100"
  backend-feed:
    image: maduflavins/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: 'udermicroservice'
      POSTGRESS_PASSWORD: 'udermicroservice' 
      POSTGRESS_DB: 'postgres' 
      POSTGRESS_HOST: 'udermicroservice.cgmpimwngkbt.us-east-2.rds.amazonaws.com' 
      AWS_REGION: 'us-east-2' 
      AWS_PROFILE: 'profile'
      AWS_BUCKET: 'udermicroservice'
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: maduflavins/udacity-frontend
    ports:
      - "8100:80"
